version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/root/api"]
    ports:
      - "3000:3000"
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/root/worker"]
