name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Alibaba Cloud Registry
        env:
          REGISTRY_URL: ${{ secrets.ALIYUN_REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        run: |
          echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin $REGISTRY_URL

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64   # 支持多平台
          tags: |
            ${{ secrets.ALIYUN_REGISTRY_URL }}/temporal-releaser/temporal-releaser:latest
          metadata: true          # 让docker/build-push-action生成元数据
          file: Dockerfile

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose pull
            docker-compose up -d
